version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_passwords
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/usr/src/app  # ホストとコンテナの同期
      - /usr/src/app/node_modules  # node_modulesはコンテナ内に保持
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres_user
      - DATABASE_PASSWORD=postgres_password
      - DATABASE_NAME=app_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app  # ホストとコンテナのファイル同期
      - /usr/src/app/node_modules  # node_modulesはコンテナ内に保持
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
